compile filter="":
  #!/usr/bin/env bash
  
  find . -name "*.typ" -name "*{{filter}}*" -not -name "doc.typ" | while read -r file; do
    base="${file%.typ}"
    echo "compiling $base" >&2
    typst compile --input='dark=false' --ppi 350 "$file" "assets/${base}-light.png"
    echo "   light done" >&2
    typst compile --input='dark=true' --ppi 350 "$file" "assets/${base}-dark.png"
    echo "   dark done" >&2
  done
